<TrackerView>:
    messages: 1000 # amount of messages stored in client logs.
    cols: 1
    viewclass: 'SelectableLabel'
    scroll_y: 0
    scroll_type: ["content", "bars"]
    bar_width: dp(12)
    effect_cls: "ScrollEffect"
    SelectableRecycleBoxLayout:
        default_size: None, dp(20)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(3)

<CheckItem>:
    size_hint: None, None
    size: self.minimum_size
    MDCheckbox:
        id: checkitem_box
        active: root.active
        on_active: root.active = self.active
    MDLabel:
        id: checkitem_label
        adaptive_size: True
        text: root.text

<ItemTracker>:
    AnchorLayout:
        size_hint: 1, 1
        anchor_x: "center"
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            size_hint: None, None
            height: root.height
            width: root.minimum_width
            StackLayout:
                size_hint: 1, None
                size: self.minimum_size
                spacing: 2
                id: item_tracker_full

<VisualTracker>:
    BoxLayout:
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            size_hint: None, None
            width: 0
            height: root.height
            StackLayout:
                size_hint: 1, None
                size: self.minimum_size
                spacing: 2
                id: item_tracker_left
        BoxLayout:
            orientation: "vertical"
            BoxLayout:
                orientation: "horizontal"
                pos_hint: {'center_x': 0.5}
                size_hint: None, None
                size: self.minimum_size
                padding: [12,8]
                spacing: 16
                CheckItem:
                    id: auto_tab_checkitem
                    text: "Auto Tab"
                    active: app.auto_tab
                    pos_hint: {'center_y': 0.5}
                    on_active: app.on_auto_tab_active(*args)
                MDDropDownItem:
                    id: map_list
                    on_release: app.open_map_dropdown(self)
                    MDDropDownItemText:
                        id: drop_text
                        text: "Current Map: " + app.current_map
                MDButton:
                    style: "outlined"
                    size_hint: None, None
                    height: dp(32)
                    pos_hint: {'center_y': 0.5}
                    radius: [dp(4),dp(4),dp(4),dp(4)]
                    on_release: tracker_map_container.recenter_view()
                    MDButtonText:
                        text: "Recenter"
                        font_style: "Label"
                        role: "medium"

            BoxStencil:
                ScrollWheelZoomScatterLayout:
                    id: tracker_map_container
                    do_rotation: False
                    auto_bring_to_front: False
                    scale_min: 0.2
                    scale_max: 20.0
                    
                    ApAsyncImage:
                        id: tracker_map
                        source: app.source
                        fit_mode: "contain"
                        pos_hint: {'x': 0, 'y': 0}

                    Widget:
                        id: location_canvas
                        pos_hint: {'x': 0, 'y': 0}
                        canvas.before:
                            PushMatrix:
                            Rotate:
                                #make top left 0,0 like poptracker
                                origin: tracker_map.center
                                angle: 180
                                axis: 1, 0, 0
                            Translate:
                                #scale location_canvas with tracker_map to match resizing
                                xy: (tracker_map.x + (tracker_map.width - tracker_map.norm_image_size[0])/2, tracker_map.y + (tracker_map.height - tracker_map.norm_image_size[1])/2)
                            Scale:
                                #scale coords by original size so we can use coords for full image
                                origin: 0,0
                                x: tracker_map.norm_image_size[0] / tracker_map.texture_size[0] if tracker_map.texture_size[0] > 0 else 1
                                y: tracker_map.norm_image_size[1] / tracker_map.texture_size[1] if tracker_map.texture_size[1] > 0 else 1
                        canvas.after:
                            #close transformations in after canvas so all objects get transformed
                            PopMatrix:
            ScrollView:
                do_scroll_x: True
                do_scroll_y: False
                size_hint: None, None
                width: self.parent.width
                height: 0
                StackLayout:
                    orientation: "tb-lr"
                    size_hint: None, 1
                    size: self.minimum_size
                    spacing: 2
                    id: item_tracker_bottom
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            size_hint: None, None
            width: 0
            height: root.height
            StackLayout:
                size_hint: 1, None
                size: self.minimum_size
                spacing: 2
                id: item_tracker_right

<UTTextColor>:
    in_logic: "20ff20"
    out_of_logic: "cf1010"
    glitched: "ffff20"
    collected: "3F3F3F"
    collected_light: "FFFFFF"
    in_logic_glitched: "afff20"
    out_of_logic_glitched: "ef5500"
    mixed_logic: "ff9f20"
    hinted:"3040ff"
    hinted_in_logic:"20ffff"
    hinted_out_of_logic:"c010ff"
    hinted_glitched:"ff9f20"
    excluded: "CFCFCF"
    excluded_glitched: "ef5500"
    unconnected: "89F336"
    error: "FF0000"
    default: "FFFFFF"
    ut_status: "FFFFFF"
<ApAsyncImage>:

<ApLocationIcon>:
    id: location_icon
    size: (0,0)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    canvas.before:
        PushMatrix:
        Rotate:
            origin: location_icon.center
            angle: 180
            axis: 1, 0, 0
        Translate:
            xy: (-location_icon.norm_image_size[0]/2,location_icon.norm_image_size[1]/2)
    canvas.after:
        #close transformations in after canvas so all objects get transformed
        PopMatrix:

<TrackerTooltip>:
    pos_hint: {}

<ApLocationDeferred>:
    text: "Server:"
    size_hint_x: None
    canvas.before:
        PushMatrix:
        Rotate:
            origin: (self.x, self.y)
            angle: 45
        Scale:
            origin: (self.x, self.y)
            x: .7 # aprox sqrt(2)
            y: .7 # aprox sqrt(2)
    canvas:
        Color:
            rgb: 0,0,0 
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color #set by ApLocation.update_color()
        Rectangle:
            pos: self.x-self.width/2, self.y-self.height/2
            size: self.size
    canvas.after:
        #close transformations in after canvas so all objects get transformed
        PopMatrix:

<ApLocationMixed>:
    text: "Server:"
    size_hint_x: None
    canvas:
        Color:
            rgb: 0,0,0 
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color #set by ApLocation.update_color()
        Rectangle:
            pos: self.x-self.width/2, self.y-self.height/2
            size: self.size

<ApLocationSplit>:
    text: "Server:"
    size_hint_x: None
    color_2: (1, 0, 0)
    color_4: (1, 1, 0)
    color_1: (0, 1, 0)
    color_3: (0, 0, 1)
    canvas:
        Color:
            rgb: 0,0,0 
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color_1
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y + (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_3
        Triangle:
            points: self.x, self.y, self.x + (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_2
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y - (self.height /2)
        Color:
            rgb: self.color_4
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x - (self.width / 2), self.y + (self.height /2)

<ApItemGridHeader>:
    bold: True
    size_hint: 1, None
    size: self.texture_size
    halign: "center"
    valign: "center"
    padding: 4

<ApItemGrid>:
    size_hint: None, None

<ApItemIcon>:
    size_hint: None, None

    canvas.after:
        Color: 
            rgb: self.marker_color
            a: self.marker_alpha
        Line:
            width: 1
            rectangle: self.x + 1, self.y + 1, self.width - 1, self.height - 1

<ApCounter>:
    bold: True
    size_hint: 1, 1
    text_size: self.size
    halign: "right"
    valign: "bottom"
    padding: 2, 1
    outline_width: 2
    outline_color: 0, 0, 0